# http://docs.travis-ci.com/user/languages/r/
language: r

sudo: required

r_github_packages:
  - jimhester/covr
  
after_success:
  - Rscript -e 'library(covr);coveralls()'
  
warnings_are_errors: false

notifications:
  email:
    - zozlak@zozlak.org