language: r

before_install:

apt_packages:

brew_packages:

r_binary_packages:

r_packages: 

r_github_packages: 

after_success:
  - Rscript -e 'library(covr);coveralls()'
  
warnings_are_errors: false

notifications:
  email:
    - zozlak@zozlak.org