# http://docs.travis-ci.com/user/languages/r/
language: r

sudo: required

after_success:
  - Rscript -e 'library(covr);coveralls()'
  
warnings_are_errors: false

notifications:
  email:
    - zozlak@zozlak.org